---
- name: check if satellite is answering
  uri:
    url: "https://{{ satellite_hostname }}.{{ satellite_domain }}/api/organizations"
    user: "{{ satellite_user }}"
    password: "{{ satellite_password }}"
    force_basic_auth: yes
  register: satellite_is_installed
  ignore_errors: yes
  tags: [ always ]

- set_fact:
    satellite_is_installed: "{{ False if satellite_is_installed.failed | default(False) or satellite_is_installed.status != 200 else True }}"
  tags: [ always ]
