---
- name: check for yum updates
  shell: yum check-update --quiet | grep -v "^$\|installed\|running" | wc -l
  args:
    warn: false
  register: yum_updates
  changed_when: yum_updates.stdout != "0"

- name: upgrade all packages
  command: yum -y update
  args:
    warn: false
  when: yum_updates.stdout != "0"

- name: replace ntp with chrony
  when: setup_chrony
  block:
    - name: remove ntp
      yum:
        name: "ntp,ntpdate"
        state: absent

    - name: install chrony
      yum:
        name: "chrony"
        state: present

    - name: start chrony
      systemd:
        name: chronyd
        state: started
        enabled: yes

- name: Install Satellite packages
  yum:
    name: "{{ satellite_packages }}"
    state: present
