---
# tasks file for satellite

- name: check if satellite is already up and listening
  import_tasks: check-satellite-state.yml

- name: ensure required repos are present
  import_tasks: repos.yml
  tags: [satellite-packages, satellite]
  when: not satellite_is_installed

- name: ensure firewall ports are enabled
  import_tasks: network.yml
  tags: [satellite-networks, satellite]

- name: install the satellite server
  import_tasks: satellite_install.yml
  tags: [satellite-install, satellite]
