---
- name: set hostname with hostnamectl
  hostname:
    name: "{{ satellite_hostname }}.{{ satellite_domain }}"

- name: update /etc/hosts with satellite hostname
  lineinfile:
    line: "{{ satellite_ip_address }}
      {{ satellite_hostname }}.{{ satellite_domain }}
      {{ satellite_hostname }}"
    dest: "/etc/hosts"

- name: install firewalld
  yum:
    name: firewalld
    state: present

- name: start firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: firewalld services
  firewalld:
    permanent: true
    immediate: true
    port: "{{ item }}"
    state: enabled
  with_items: "{{ satellite_firewall_ports }}"
