---
# vim: sw=2 ts=102 ai
- include: satellite_helper_filter.yml months_ago=4 environments=Development,Testing,Production
  when: satellite_hammer_configure_CV_filters
- include: satellite_helper_filter.yml months_ago=3 environments=Development,Testing
  when: satellite_hammer_configure_CV_filters
- include: satellite_helper_filter.yml months_ago=2 environments=Development
  when: satellite_hammer_configure_CV_filters
- include: satellite_helper_filter.yml months_ago=1 environments=''
  when: satellite_hammer_configure_CV_filters
