---
- name: check for yum updates
  shell: yum check-update --quiet | grep -v "^$\|installed\|running" | wc -l
  args:
    warn: false
  register: yum_updates
  changed_when: yum_updates.stdout != "0"

- name: upgrade all packages
  command: yum -y update
  args:
    warn: false
  when: yum_updates.stdout != "0"

- name: replace ntp with chrony
  when: setup_chrony
  block:
    - name: remove ntp
      yum:
        name: "ntp,ntpdate"
        state: absent

    - name: install chrony
      yum:
        name: "chrony"
        state: present

    - name: start chrony
      systemd:
        name: chronyd
        state: started
        enabled: yes

- name: Install Satellite packages
  yum:
    name: "{{ satellite_packages }}"
    state: present

- name: run satellite-installer --scenario satellite
  shell: |
    satellite-installer --scenario satellite -v --force \
    --foreman-initial-location {{ satellite_default_location }} \
    --foreman-initial-organization {{ satellite_default_organization }} \
    {% if satellite_enable_tftp %}--foreman-proxy-tftp=true {% endif %} \
    {% if satellite_enable_discovery %}--enable-foreman-plugin-discovery \
    --foreman-proxy-plugin-discovery-install-images=true \
     {% endif %} \
    {% if satellite_enable_proxy_template %}--foreman-proxy-templates=1 {% endif %}\
    --foreman-initial-admin-username {{ satellite_user }} \
    --foreman-initial-admin-password {{ satellite_password }}
  when: not satellite_is_installed or force_run_installer

- name: check if satellite is up and answering
  include_tasks: check-satellite-state.yml

- name: fail if satellite isn't running
  fail:
    msg: "Was not able to ensure only the required repos for satellite installation are enabled"
  when: not satellite_is_installed

- name: create hammer auth directory
  file:
    path: ~/.hammer
    state: directory
    mode: 0755

- name: copy configuration for hammer
  template:
    src: hammer_cli_config.yml.j2
    dest: ~/.hammer/cli_config.yml
  when: deploy_hammer_cli_config|bool