---
# vim: sw=2 ts=102 ai

- name: install satellite
  shell: |
    satellite-installer --scenario satellite -v --force \
    --foreman-initial-location {{ satellite_default_location }} \
    --foreman-initial-organization {{ satellite_default_organization }} \
    --foreman-admin-username {{ satellite_user }} \
    --foreman-admin-password {{ satellite_pass }} \
    --foreman-proxy-tftp true \
    --foreman-plugin-discovery-install-images true \
    --capsule-puppet true \
    --foreman-proxy-puppetca true \
    --enable-foreman-plugin-discovery
  when: not satellite_is_installed

- name: create hammer auth directory
  file:
    path: ~/.hammer
    state: directory
    mode: 0755

- name: copy configuration for hammer
  template:
    src: hammer_cli_config.yml.j2
    dest: ~/.hammer/cli_config.yml

- name: create /usr/local/bin
  file:
    path: /usr/local/bin
    state: directory
    mode: 0755

- name: copy pulp-admin helper script
  copy:
    src: pulp-admin.sh
    dest: /usr/local/bin/pulp-admin.sh
    mode: 0755
    owner: root
    group: root

- name: copy alternative sources if defined
  template:
    src: alternative.conf.j2
    dest: /etc/pulp/content/sources/conf.d/alternative.conf
  register: copy_alt_sources
  when: 'pulp_mirror is defined and pulp_mirror != ""'

- name: kick off index of pulp alternative sources
  command: /usr/local/bin/pulp-admin.sh content sources refresh --bg
  when: copy_alt_sources.changed
