---
# vim: sw=2 ts=102 ai
- name: Check KS content-view has a published version
  command: "/usr/bin/hammer --output json content-view info --name '{{ CV }}-Kickstart' {{ORG}}"
  register: hammer_output
  changed_when: "{{ (hammer_output.stdout | from_json).Versions | length == 0 }}"

- name: publish KS content-view if needed
  command: "/usr/bin/hammer content-view publish --name '{{ item.Name }}' --description 'First publish' {{ORG}}"
  when: hammer_output.changed
  with_items: [ "{{ hammer_output.stdout | from_json }}" ]
